use_frameworks!

target 'FlapjackExample' do
  platform :ios, "11.0"

  pod 'SwiftLint', '0.27.0'

  pod 'Flapjack/Core', path: '../', testspecs: %w(Tests)
  pod 'Flapjack/CoreData', path: '../', testspecs: %w(Tests)
  pod 'Flapjack/UIKit', path: '../'

  # target 'Tests' do
  #   inherit! :search_paths

    
  # end
end
