use_frameworks!

target 'FlapjackExample' do
  platform :ios, "10.3"

  pod 'SwiftLint', '0.27.0'

  # Specify Flapjack at the top level with its tests.
  pod 'Flapjack', path: '../', testspecs: %w(Tests)
  # These two do not have their own tests (yet).
  pod 'Flapjack/CoreData', path: '../'
  pod 'Flapjack/UIKit', path: '../'

  # target 'Tests' do
  #   inherit! :search_paths

    
  # end
end
