# Reference:
# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules:
  # Disable rules that are in the default set
  - colon  # Disabled because it's too restrictive. See realm/SwiftLint#1901
  - large_tuple  # Maybe? What's the length for this, 2?
  - line_length  # Maybe? What's the length for this?
  - file_name
  - no_fallthrough_only
  - notification_center_detachment
  - vertical_whitespace  # Can I make this "no more than 2?"
  # The following are disabled by default anyway
  - multiline_function_chains  # I'd like to enable this someday
  - multiline_parameters  # I'd like to enable this someday
  - multiline_arguments  # I'd like to enable this someday
  - object_literal  # I'd like to enable this someday
  - pattern_matching_keywords  # I'd like to enable this someday
  - private_action  # I'd like to enable this someday
  - private_outlet  # I'd like to enable this someday
  - single_test_class  # I'd like to enable this someday
  - todo  # I'd like to enable this someday
  - unavailable_function  # I'd like to enable this someday
  - xctfail_message  # I'd like to enable this someday
opt_in_rules: 
  # Enable rules not in the default set
  - anyobject_protocol
  - array_init
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier  # Maybe?
  - fallthrough
  - fatal_error_message
  - file_name  # Maybe?
  - first_where
  - function_default_parameter_at_end
  - joined_default_parameter
  - lower_acl_than_parent
  - modifier_order
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - required_enum_case  # Maybe?
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  # The following are default rules that are already enabled
  - multiple_closures_with_trailing_closure  # Maybe?
  - redundant_type_annotation  # Maybe?

included:
  - Flapjack  # CocoaPods code
  - Example  # Example project code

cyclomatic_complexity:
  warning: 12
